version: '3.8'
services:
  pg:
    container_name: pg_jdbc
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DB=pg-jdbc