spring:
  main:
    banner-mode: "off"

server:
  address: 0.0.0.0

jdbc:
  # driverClassName: org.postgresql.Driver
  url: ${DATABASE_URL}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
