spring:
  profiles:
    default: development

server:
  port: 3000
  servlet:
    context-path: /api
  shutdown: graceful

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tryItOutEnabled: true
    docExpansion: list
    syntaxHighlight:
      theme: nord
